version: '3'

services:
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './collector.yaml:/otel-collector-config.yaml'
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"